apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api-deployment
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api-container
        image: gcr.io/roidtc-oct-user600/internal:1
        env: 
        - name: PORT
          value: "8082"
        - name: GOOGLE_CLOUD_PROJECT
          value: "roidtc-oct-user600"
        ports:
        - containerPort: 8082
            
        
